//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nov20Assignment4_Hannah_Gracie.KRInstructors
{


    public partial class instructorpage
    {
    }
}
